import streamlit as st
import anthropic

st.set_page_config(
    page_title="AI Summary — DataDart",
    page_icon="🤖",
    layout="wide"
)

# ── Custom CSS ──────────────────────────────────────────────────────────────
st.markdown("""
<style>
.section-header {
    background: linear-gradient(90deg, #1a4a7a 0%, #1a6aaa 100%);
    color: white;
    padding: 10px 20px;
    border-radius: 8px;
    font-size: 18px;
    font-weight: 600;
    margin: 20px 0 10px 0;
}
.exec-box {
    background-color: #f0f7ff;
    border-left: 5px solid #1a6aaa;
    padding: 16px 20px;
    border-radius: 6px;
    margin-bottom: 12px;
    font-size: 15px;
    line-height: 1.8;
    white-space: pre-wrap;
}
.summary-banner {
    background: linear-gradient(135deg, #0d2b4e 0%, #1a5a9a 100%);
    color: white;
    padding: 24px 32px;
    border-radius: 12px;
    margin-bottom: 20px;
}
.summary-banner h2 {
    color: white;
    font-size: 26px;
    margin: 0 0 6px 0;
}
.summary-banner p {
    color: rgba(255,255,255,0.85);
    font-size: 14px;
    margin: 0;
}
</style>
""", unsafe_allow_html=True)

def call_claude(prompt: str) -> str:
    if "ANTHROPIC_API_KEY" not in st.secrets:
        st.error("⚠️ Anthropic API key not found. Add ANTHROPIC_API_KEY to Streamlit secrets.")
        st.stop()
    client = anthropic.Anthropic(api_key=st.secrets["ANTHROPIC_API_KEY"])
    msg = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=2000,
        messages=[{"role": "user", "content": prompt}]
    )
    return msg.content[0].text

def build_profile_text(df) -> str:
    import pandas as pd
    numeric_df = df.select_dtypes(include="number")
    char_df    = df.select_dtypes(include="object")
    lines = []
    lines.append(f"Rows: {df.shape[0]:,}, Columns: {df.shape[1]}")
    lines.append(f"Numeric columns: {numeric_df.columns.tolist()}")
    lines.append(f"Categorical columns: {char_df.columns.tolist()}")
    lines.append("\nNumeric summary:")
    lines.append(numeric_df.describe().round(2).to_string())
    lines.append("\nCategorical top values:")
    for col in char_df.columns[:8]:
        top = df[col].value_counts().head(5).to_dict()
        lines.append(f"  {col}: {top}")
    lines.append(f"\nMissing values:\n{df.isnull().sum().to_string()}")
    return "\n".join(lines)

# ── Back button ────────────────────────────────────────────────────────────────
st.page_link("app.py", label="← Back to DataDart", icon="🎯")
st.divider()

# ── Check session state for data ───────────────────────────────────────────────
if "df" not in st.session_state or st.session_state["df"] is None:
    st.warning("⚠️ No dataset loaded. Please go back to DataDart and upload a file first.")
    st.page_link("app.py", label="Go to DataDart →", icon="🎯", use_container_width=True)
    st.stop()

df       = st.session_state["df"]
filename = st.session_state.get("filename", "your dataset")
profile  = build_profile_text(df)

# ── Page banner ────────────────────────────────────────────────────────────────
st.markdown(f"""
<div class="summary-banner">
    <h2>🤖 AI Executive Summary</h2>
    <p>Dataset: <strong>{filename}</strong> &nbsp;·&nbsp;
    {df.shape[0]:,} rows × {df.shape[1]} columns &nbsp;·&nbsp;
    Generated by Claude AI</p>
</div>
""", unsafe_allow_html=True)

# ── Generate button ────────────────────────────────────────────────────────────
if st.button("✨ Generate Full AI Summary", type="primary", use_container_width=True):

    # Executive Summary
    st.markdown("---")
    st.markdown("### 📋 Executive Summary")
    with st.spinner("Claude is reading your data..."):
        exec_text = call_claude(f"""
You are a senior data analyst. Analyze this dataset profile and write:
1. A 2-3 sentence executive summary of what this dataset contains
2. 6-8 key bullet point insights with specific numbers from the data
3. 2-3 watch-out flags or data quality observations

Format exactly like this:

EXECUTIVE SUMMARY
[your 2-3 sentence summary]

KEY INSIGHTS
[bullet insights with specific numbers]

WATCH-OUTS
[bullet flags]

Dataset profile:
{profile}
""")
    st.markdown(f'<div class="exec-box">{exec_text}</div>', unsafe_allow_html=True)

    # Analysis Tables
    st.markdown("---")
    st.markdown("### 📊 Analysis Tables")
    with st.spinner("Generating analysis tables..."):
        tables_text = call_claude(f"""
You are a senior data analyst. Generate 3 meaningful analysis tables.
For each: pick a relevant categorical grouping, aggregate key numeric columns,
show top 5-6 rows, format as markdown table, add a 1-line insight below.
Use clear bold titles.

Dataset profile:
{profile}
""")
    st.markdown(tables_text)

    # Visual Insights Narrative
    st.markdown("---")
    st.markdown("### 👁️ Visual Insights Narrative")
    with st.spinner("Writing visual insights..."):
        visual_text = call_claude(f"""
You are a senior data analyst. Cover these four areas with headers and bullets:
1. KEY DISTRIBUTIONS
2. RELATIONSHIPS AND TRENDS
3. RECOMMENDED VISUALIZATIONS
4. ANOMALIES AND OUTLIERS
Be specific with column names and numbers.

Dataset profile:
{profile}
""")
    st.markdown(visual_text)

    st.success("✅ AI Summary complete!")

else:
    st.info("Click the button above to generate the full AI-powered summary for your dataset.")

# ── Footer ──────────────────────────────────────────────────────────────────────
st.divider()
st.markdown("""
<div style="text-align: center; padding: 16px 0 8px 0;
            color: #888; font-size: 13px;">
    © 2026 <strong>DataDart</strong> · 🎯 Datadart — All rights reserved. ·
    Powered by <strong>Claude AI</strong> + <strong>Streamlit</strong><br>
    <span style="font-size: 11px; opacity: 0.7;">
    Your data never leaves your session · No data is stored or shared.
    </span>
</div>
""", unsafe_allow_html=True)
